services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: "${DATABASE_URL}"

    container_name: tiket_app
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: "${DATABASE_URL}"
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "${NEXTAUTH_SECRET:-ganti_dengan_openssl_rand_base64_32}"
      N8N_WEBHOOK_URL: "${N8N_WEBHOOK_URL:-}"

    networks:
      - tiket_network

networks:
  tiket_network:
    driver: bridge